name: Common Build Steps

on:
  workflow_call:
    outputs:
      build-path:
        description: "Path to the built website files"
        value: www

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Rust toolchain ğŸ¦€
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rust-src

      - name: Install wasm-pack ğŸ“¦
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Wasm and Site ğŸ› ï¸
        run: npm run build
        env:
          CARGO_TERM_COLOR: always
